---
# ansible plyabook for install ntp

- name: install ntp
  yum: name=ntp state=present

- name: remove default localtime
  file: path=/etc/localtime state=absent

- name: set timezone
  file: src=/usr/share/zoneinfo/Asia/Tokyo
        dest=/etc/localtime
        state=link

- name: put ntp.conf
  template:
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644

- name: service ntpd start
  service: name=ntpd state=started enabled=yes
