---
# ansible playbook for installing php

- name: install php
  yum: name={{ item }} enablerepo=remi-php55 state=present
  with_items:
    - php
    - php-fpm
    - php-mbstring
    - php-mysqlnd
    - php-pdo
    - php-xml

- name: start php-fpm service
  service: name=php-fpm state=started enabled=yes

- name: put www.conf
  template:
    src=www.conf.j2
    dest=/etc/php-fpm.d/www.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart php-fpm